/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gymplanner;

/**
 *
 * @author User
 */
import java.time.LocalDate;
import java.time.YearMonth;
import javax.swing.table.DefaultTableModel;

public class Profile extends javax.swing.JFrame {
    
private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Profile.class.getName());
 private boolean isInitializing = true; // Flag to prevent premature triggers

    public Profile() {
        initComponents();
        
        // 1. Fill Month ComboBox
        comboMonth.removeAllItems();
        String[] months = {
            "January", "February", "March", "April", "May", "June", 
            "July", "August", "September", "October", "November", "December"
        };
        for (String month : months) {
            comboMonth.addItem(month);
        }

        // 2. Fill Year ComboBox (2020 to 2035)
        comboYear.removeAllItems();
        for (int y = 2020; y <= 2035; y++) {
            comboYear.addItem(String.valueOf(y));
        }

        // 3. Set default to current month/year
        LocalDate now = LocalDate.now();
        comboMonth.setSelectedIndex(now.getMonthValue() - 1);
        comboYear.setSelectedItem(String.valueOf(now.getYear()));

        // 4. Finished setup, enable updates and load calendar
        isInitializing = false;
        updateCalendar();
    }

    public void updateCalendar() {
        int selectedMonth = comboMonth.getSelectedIndex() + 1; // 1 to 12
        int selectedYear = Integer.parseInt((String) comboYear.getSelectedItem());
        
        populateCalendar(selectedYear, selectedMonth);
    }

    public void populateCalendar(int year, int month) {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        model.setRowCount(0);
        model.setRowCount(6);
        
        YearMonth yearMonth = YearMonth.of(year, month);
        int daysInMonth = yearMonth.lengthOfMonth();
        
        LocalDate firstOfMonth = yearMonth.atDay(1);
        int startDayOfWeek = firstOfMonth.getDayOfWeek().getValue() % 7;
        
        int currentDay = 1;
        for (int row = 0; row < 6; row++) {
            for (int col = 0; col < 7; col++) {
                if (row == 0 && col < startDayOfWeek) {
                    model.setValueAt("", row, col);
                } else if (currentDay <= daysInMonth) {
                    model.setValueAt(currentDay, row, col);
                    currentDay++;
                } else {
                    model.setValueAt("", row, col);
                }
            }
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        comboYear = new javax.swing.JComboBox<>();
        comboMonth = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 114, 375, 193));

        comboYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboYear.addActionListener(this::comboYearActionPerformed);
        getContentPane().add(comboYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        comboMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboMonth.addActionListener(this::comboMonthActionPerformed);
        getContentPane().add(comboMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("Profille:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setText("Calendar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        jButton1.setText("Summary");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();
    int col = jTable1.getSelectedColumn();
    
    if (row != -1 && col != -1) {
        Object dayValue = jTable1.getValueAt(row, col);
        
        if (dayValue != null && !dayValue.toString().trim().isEmpty()) {
            int day = Integer.parseInt(dayValue.toString());
            int month = comboMonth.getSelectedIndex() + 1;
            int year = Integer.parseInt((String) comboYear.getSelectedItem());
            
            LocalDate selectedDate = LocalDate.of(year, month, day);
            System.out.println("Full Selected Date: " + selectedDate); 
            // Output format example: 2026-09-15
        }
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void comboYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboYearActionPerformed
        // TODO add your handling code here:
        if (!isInitializing && comboMonth.getSelectedItem() != null && comboYear.getSelectedItem() != null) {
        updateCalendar();
    }

    }//GEN-LAST:event_comboYearActionPerformed

    private void comboMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMonthActionPerformed
        // TODO add your handling code here:
       if (!isInitializing && comboMonth.getSelectedItem() != null && comboYear.getSelectedItem() != null) {
        updateCalendar();
    }


    }//GEN-LAST:event_comboMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Profile().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboMonth;
    private javax.swing.JComboBox<String> comboYear;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
